// Generated by gen:sdk — do not edit by hand
// Source: specs/openapi/email.yaml
// Regenerate: pnpm gen:sdk

// ── Types ──────────────────────────────────────────────────────────────────

export interface EmailAddress {
  /** Display name, or null if not set. */
  name: string | null;
  /** Email address. */
  email: string;
}

export interface MailboxResponse {
  /** Unique mailbox identifier (UUID). */
  id: string;
  /** Full email address for this mailbox. */
  address: string;
  /** Local part of the email address. */
  username: string;
  /** Domain of the email address. */
  domain: string;
  /** Current mailbox status. */
  status: "active" | "expired" | "deleted";
  /** ISO 8601 timestamp of mailbox creation. */
  created_at: string;
  /** ISO 8601 expiry timestamp, or null if the mailbox does not expire. */
  expires_at: string | null;
}

export interface MailboxListResponse {
  mailboxes: MailboxResponse[];
  /** Total number of mailboxes for this wallet. */
  total: number;
  /** Current page number. */
  page: number;
  /** Number of items per page. */
  per_page: number;
}

export interface EmailMessage {
  /** Message ID (JMAP object ID). */
  id: string;
  from: EmailAddress;
  to: EmailAddress[];
  /** Email subject line. */
  subject: string;
  /** ISO 8601 timestamp when the message was received. */
  received_at: string;
  /** Message size in bytes. */
  size: number;
  /** Whether the message has attachments. */
  has_attachment: boolean;
  /** Short plain-text preview of the message body. */
  preview: string;
}

export interface EmailDetail {
  /** Message ID (JMAP object ID). */
  id: string;
  from: EmailAddress;
  to: EmailAddress[];
  /** Email subject line. */
  subject: string;
  /** ISO 8601 timestamp when the message was received. */
  received_at: string;
  /** Message size in bytes. */
  size: number;
  /** Whether the message has attachments. */
  has_attachment: boolean;
  /** Short plain-text preview of the message body. */
  preview: string;
  /** CC recipients. */
  cc: EmailAddress[];
  /** Plain-text body, or null if not present. */
  text_body: string | null;
  /** HTML body, or null if not present. */
  html_body: string | null;
}

export interface EmailListResponse {
  messages: EmailMessage[];
  /** Total number of messages in this mailbox. */
  total: number;
  /** Zero-based position of the first result in the full list. */
  position: number;
}

export interface WebhookResponse {
  /** Webhook ID (UUID). */
  id: string;
  /** Destination URL for webhook events. */
  url: string;
  /** Event types this webhook listens for. */
  events: string[];
  /** Webhook status. */
  status: string;
  /** ISO 8601 timestamp of webhook registration. */
  created_at: string;
}

export interface WebhookListResponse {
  webhooks: WebhookResponse[];
  /** Total number of webhooks for this mailbox. */
  total: number;
}

export interface DnsRecord {
  /** DNS record type (e.g. MX, TXT, CNAME). */
  type: string;
  /** DNS record name (host). */
  name: string;
  /** DNS record value. */
  content: string;
  /** MX record priority (only for MX records). */
  priority?: number;
}

export interface DomainResponse {
  /** Domain ID (UUID). */
  id: string;
  /** Registered domain name. */
  domain: string;
  /** Verification status of the domain. */
  status: string;
  /** Ethereum address of the wallet that registered this domain. */
  owner_wallet: string;
  /** ISO 8601 timestamp of domain registration. */
  created_at: string;
  /** ISO 8601 timestamp of domain verification, or null if not yet verified. */
  verified_at: string | null;
  /** DNS records you must add to your domain for verification. */
  required_records: DnsRecord[];
  /** DKIM records to add after verification. Only present for verified domains. */
  dkim_records?: DnsRecord[];
}

export interface DomainListResponse {
  domains: DomainResponse[];
  /** Total number of domains registered by this wallet. */
  total: number;
  /** Current page number. */
  page: number;
  /** Number of items per page. */
  per_page: number;
}

export interface VerificationResult {
  /** DNS record type checked. */
  type: string;
  /** DNS name checked. */
  name: string;
  /** Expected DNS record value. */
  expected: string;
  /** Actual DNS record value found, or null if not present. */
  found: string | null;
  /** Whether the check passed. */
  pass: boolean;
}

export interface VerifyDomainResponse {
  /** Domain ID (UUID). */
  id: string;
  /** Domain name. */
  domain: string;
  /** Verification status after the check. */
  status: string;
  /** ISO 8601 timestamp of successful verification, or null if still pending. */
  verified_at: string | null;
  /** Per-record verification results. Present when status is not already verified. */
  verification_results?: VerificationResult[];
  /** DKIM records to add now that the domain is verified. Present on successful verification. */
  dkim_records?: DnsRecord[];
}

export interface CreateMailboxRequest {
  /** Desired local part of the email address. Generated randomly if omitted. */
  username?: string;
  /** Email domain to use. Must be a verified custom domain or the shared default domain. */
  domain?: string;
  /** Mailbox lifetime in milliseconds. Defaults to 7 days (604800000). Pass null for no expiry. */
  ttl_ms?: number;
}

export interface RenewMailboxRequest {
  /** Additional milliseconds to extend the mailbox TTL. Defaults to 7 days (604800000). */
  ttl_ms?: number;
}

export interface SendMessageRequest {
  /** Recipient email address. */
  to: string;
  /** Email subject line. */
  subject: string;
  /** Plain-text message body. */
  body?: string;
  /** HTML message body. Can be provided alongside `body` for multipart messages. */
  html?: string;
  /** CC recipient email address. */
  cc?: string;
  /** BCC recipient email address. */
  bcc?: string;
}

export interface RegisterWebhookRequest {
  /** HTTPS URL to receive webhook events. */
  url: string;
  /** Optional signing secret. Used to generate HMAC-SHA256 signatures. */
  secret?: string;
  /** Event types to subscribe to. Defaults to all events. */
  events?: string[];
}

export interface RegisterDomainRequest {
  /** Domain name to register (e.g. "example.com"). */
  domain: string;
}

export interface ListMailboxesParams {
  /** Number of mailboxes per page (1–100, default 20). */
  limit?: number;
  /** Page number (1-based, default 1). */
  page?: number;
}

export interface GetMailboxParams {
  /** Mailbox ID. */
  id: string;
}

export interface DeleteMailboxParams {
  /** Mailbox ID. */
  id: string;
}

export interface RenewMailboxParams {
  /** Mailbox ID. */
  id: string;
}

export interface ListMessagesParams {
  /** Mailbox ID. */
  id: string;
  /** Maximum number of messages to return (1–100, default 20). */
  limit?: number;
  /** Zero-based position offset to start from (default 0). */
  position?: number;
}

export interface GetMessageParams {
  /** Mailbox ID. */
  id: string;
  /** Message ID. */
  msgId: string;
}

export interface SendMessageParams {
  /** Mailbox ID. */
  id: string;
}

export interface RegisterWebhookParams {
  /** Mailbox ID. */
  id: string;
}

export interface ListWebhooksParams {
  /** Mailbox ID. */
  id: string;
}

export interface DeleteWebhookParams {
  /** Mailbox ID. */
  id: string;
  /** Webhook ID. */
  whId: string;
}

export interface ListDomainsParams {
  /** Number of domains per page (1–100, default 20). */
  limit?: number;
  /** Page number (1-based, default 1). */
  page?: number;
}

export interface GetDomainParams {
  /** Domain ID. */
  id: string;
}

export interface DeleteDomainParams {
  /** Domain ID. */
  id: string;
}

export interface VerifyDomainParams {
  /** Domain ID. */
  id: string;
}

export interface DeleteMailboxResponse {
  id: string;
  deleted: true;
}

export interface SendMessageResponse {
  /** Server-assigned message ID. */
  message_id: string;
  status: "sent";
}

export interface DeleteWebhookResponse {
  id: string;
  deleted: true;
}

export interface DeleteDomainResponse {
  id: string;
  deleted: true;
  /** Present if active mailboxes existed on this domain. */
  warning?: string;
}

// ── Client ─────────────────────────────────────────────────────────────────

export function createEmailClient(
  primFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
) {
  const baseUrl = "https://email.prim.sh";
  return {
    async createMailbox(req: CreateMailboxRequest): Promise<MailboxResponse> {
      const url = `${baseUrl}/v1/mailboxes`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<MailboxResponse>;
    },
    async listMailboxes(params: ListMailboxesParams): Promise<MailboxListResponse> {
      const qs = new URLSearchParams();
      if (params.limit !== undefined) qs.set("limit", String(params.limit));
      if (params.page !== undefined) qs.set("page", String(params.page));
      const query = qs.toString();
      const url = `${baseUrl}/v1/mailboxes${query ? `?${query}` : ""}`;
      const res = await primFetch(url);
      return res.json() as Promise<MailboxListResponse>;
    },
    async getMailbox(params: GetMailboxParams): Promise<MailboxResponse> {
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}`;
      const res = await primFetch(url);
      return res.json() as Promise<MailboxResponse>;
    },
    async deleteMailbox(params: DeleteMailboxParams): Promise<DeleteMailboxResponse> {
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}`;
      const res = await primFetch(url, {
        method: "DELETE",
      });
      return res.json() as Promise<DeleteMailboxResponse>;
    },
    async renewMailbox(
      params: RenewMailboxParams,
      req: RenewMailboxRequest,
    ): Promise<MailboxResponse> {
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}/renew`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<MailboxResponse>;
    },
    async listMessages(params: ListMessagesParams): Promise<EmailListResponse> {
      const qs = new URLSearchParams();
      if (params.limit !== undefined) qs.set("limit", String(params.limit));
      if (params.position !== undefined) qs.set("position", String(params.position));
      const query = qs.toString();
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}/messages${query ? `?${query}` : ""}`;
      const res = await primFetch(url);
      return res.json() as Promise<EmailListResponse>;
    },
    async getMessage(params: GetMessageParams): Promise<EmailDetail> {
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}/messages/${encodeURIComponent(params.msgId)}`;
      const res = await primFetch(url);
      return res.json() as Promise<EmailDetail>;
    },
    async sendMessage(
      params: SendMessageParams,
      req: SendMessageRequest,
    ): Promise<SendMessageResponse> {
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}/send`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<SendMessageResponse>;
    },
    async registerWebhook(
      params: RegisterWebhookParams,
      req: RegisterWebhookRequest,
    ): Promise<WebhookResponse> {
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}/webhooks`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<WebhookResponse>;
    },
    async listWebhooks(params: ListWebhooksParams): Promise<WebhookListResponse> {
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}/webhooks`;
      const res = await primFetch(url);
      return res.json() as Promise<WebhookListResponse>;
    },
    async deleteWebhook(params: DeleteWebhookParams): Promise<DeleteWebhookResponse> {
      const url = `${baseUrl}/v1/mailboxes/${encodeURIComponent(params.id)}/webhooks/${encodeURIComponent(params.whId)}`;
      const res = await primFetch(url, {
        method: "DELETE",
      });
      return res.json() as Promise<DeleteWebhookResponse>;
    },
    async registerDomain(req: RegisterDomainRequest): Promise<DomainResponse> {
      const url = `${baseUrl}/v1/domains`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<DomainResponse>;
    },
    async listDomains(params: ListDomainsParams): Promise<DomainListResponse> {
      const qs = new URLSearchParams();
      if (params.limit !== undefined) qs.set("limit", String(params.limit));
      if (params.page !== undefined) qs.set("page", String(params.page));
      const query = qs.toString();
      const url = `${baseUrl}/v1/domains${query ? `?${query}` : ""}`;
      const res = await primFetch(url);
      return res.json() as Promise<DomainListResponse>;
    },
    async getDomain(params: GetDomainParams): Promise<DomainResponse> {
      const url = `${baseUrl}/v1/domains/${encodeURIComponent(params.id)}`;
      const res = await primFetch(url);
      return res.json() as Promise<DomainResponse>;
    },
    async deleteDomain(params: DeleteDomainParams): Promise<DeleteDomainResponse> {
      const url = `${baseUrl}/v1/domains/${encodeURIComponent(params.id)}`;
      const res = await primFetch(url, {
        method: "DELETE",
      });
      return res.json() as Promise<DeleteDomainResponse>;
    },
    async verifyDomain(params: VerifyDomainParams): Promise<VerifyDomainResponse> {
      const url = `${baseUrl}/v1/domains/${encodeURIComponent(params.id)}/verify`;
      const res = await primFetch(url, {
        method: "POST",
      });
      return res.json() as Promise<VerifyDomainResponse>;
    },
  };
}
