// Generated by gen:sdk — do not edit by hand
// Source: specs/openapi/search.yaml
// Regenerate: pnpm gen:sdk

// ── Types ──────────────────────────────────────────────────────────────────

export interface SearchRequest {
  /** Search query string. */
  query: string;
  /** Maximum number of results to return. Range 1–20. */
  max_results?: number;
  /** Search depth. "advanced" uses more sources and costs more upstream compute. */
  search_depth?: "basic" | "advanced";
  /** Two-letter ISO 3166-1 alpha-2 country code to bias results. */
  country?: string;
  /** Restrict results to the given time range. */
  time_range?: "day" | "week" | "month" | "year";
  /** If true, the response includes an AI-generated answer summarizing the results. */
  include_answer?: boolean;
  /** Restrict results to these domains only. */
  include_domains?: string[];
  /** Exclude results from these domains. */
  exclude_domains?: string[];
}

export interface SearchResult {
  /** Page title. */
  title: string;
  /** Page URL. */
  url: string;
  /** Snippet text extracted from the page. */
  content: string;
  /** Relevance score between 0 and 1. */
  score: number;
  /** Publication date of the page, if available (ISO 8601). */
  published?: string;
}

export interface SearchResponse {
  /** The search query echoed back. */
  query: string;
  /** AI-generated answer summarizing results. Only present if include_answer was true. */
  answer?: string;
  /** List of search results. */
  results: SearchResult[];
  /** Time taken for the search in milliseconds. */
  response_time: number;
}

export interface ExtractRequest {
  /** URL or array of URLs to extract content from. */
  urls: string | string[];
  /** Output format for extracted content. */
  format?: "markdown" | "text";
}

export interface ExtractResult {
  /** The URL that was extracted. */
  url: string;
  /** Extracted content in the requested format. */
  content: string;
  /** Image URLs found on the page, if any. */
  images?: string[];
}

export interface FailedExtraction {
  /** The URL that failed to extract. */
  url: string;
  /** Human-readable error describing why the extraction failed. */
  error: string;
}

export interface ExtractResponse {
  /** Successfully extracted pages. */
  results: ExtractResult[];
  /** Pages that could not be extracted. */
  failed: FailedExtraction[];
  /** Time taken for the extraction in milliseconds. */
  response_time: number;
}

// ── Client ─────────────────────────────────────────────────────────────────

export function createSearchClient(primFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>) {
  const baseUrl = "https://search.prim.sh";
  return {
    async searchWeb(req: SearchRequest): Promise<SearchResponse> {
      const url = `${baseUrl}/v1/search`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<SearchResponse>;
    },
    async searchNews(req: SearchRequest): Promise<SearchResponse> {
      const url = `${baseUrl}/v1/search/news`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<SearchResponse>;
    },
    async extractUrls(req: ExtractRequest): Promise<ExtractResponse> {
      const url = `${baseUrl}/v1/extract`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<ExtractResponse>;
    },
  };
}
