// Generated by gen:sdk — do not edit by hand
// Source: specs/openapi/spawn.yaml
// Regenerate: pnpm gen:sdk

// ── Types ──────────────────────────────────────────────────────────────────

export type ServerStatus =
  | "initializing"
  | "running"
  | "off"
  | "rebuilding"
  | "migrating"
  | "destroying"
  | "deleted";

export interface PublicNet {
  ipv4?: {
    ip: string | null;
  } | null;
  ipv6?: {
    ip: string | null;
  } | null;
}

export interface ActionResponse {
  /** Action ID (provider-assigned). */
  id: string;
  /** The command that triggered this action (e.g. "start", "stop"). */
  command: string;
  /** Action status (e.g. "running", "success", "error"). */
  status: string;
  /** ISO 8601 timestamp when the action started. */
  started_at: string;
  /** ISO 8601 timestamp when the action finished, or null if still running. */
  finished_at: string | null;
}

export interface ServerResponse {
  /** Prim server ID. */
  id: string;
  /** Underlying cloud provider (e.g. "hetzner"). */
  provider: string;
  /** Provider-assigned server ID. */
  provider_id: string;
  /** Server name. */
  name: string;
  /** Server type (e.g. "small"). */
  type: string;
  status: ServerStatus;
  /** OS image slug (e.g. "ubuntu-24.04"). */
  image: string;
  /** Data center location slug (e.g. "nyc3"). */
  location: string;
  public_net: PublicNet;
  /** Ethereum address of the wallet that owns this server. */
  owner_wallet: string;
  /** ISO 8601 creation timestamp. */
  created_at: string;
}

export interface SshKeyResponse {
  /** Prim SSH key ID. */
  id: string;
  /** Underlying cloud provider. */
  provider: string;
  /** Provider-assigned SSH key ID. */
  provider_id: string;
  /** Key name. */
  name: string;
  /** SSH key fingerprint. */
  fingerprint: string;
  /** Ethereum address of the wallet that owns this key. */
  owner_wallet: string;
  /** ISO 8601 creation timestamp. */
  created_at: string;
}

export interface CreateServerRequest {
  /** Server name (provider-level label). */
  name: string;
  /** Server type slug. Only `small` is available in beta. */
  type: string;
  /** OS image slug. */
  image: string;
  /** Data center location slug. */
  location: string;
  /** Cloud provider. Defaults to Hetzner. */
  provider?: string;
  /** Array of SSH key IDs (from `POST /v1/ssh-keys`) to install. */
  ssh_keys?: string[];
  /** Cloud-init user data script to run on first boot. */
  user_data?: string;
}

export interface ResizeServerRequest {
  /** Target server type slug. */
  type: string;
  /** Whether to upgrade the disk alongside the CPU/RAM. Irreversible if true. */
  upgrade_disk?: boolean;
}

export interface RebuildServerRequest {
  /** OS image slug to rebuild with. */
  image: string;
}

export interface CreateSshKeyRequest {
  /** Human-readable label for this key. */
  name: string;
  /** The public key string (e.g. `ssh-ed25519 AAAA...`). */
  public_key: string;
}

export interface ListServersParams {
  /** Number of servers to return. Max 100. */
  limit?: number;
  /** Page number (1-indexed). */
  page?: number;
}

export interface GetServerParams {
  /** Prim server ID. */
  id: string;
}

export interface DeleteServerParams {
  /** Prim server ID. */
  id: string;
}

export interface StartServerParams {
  /** Prim server ID. */
  id: string;
}

export interface StopServerParams {
  /** Prim server ID. */
  id: string;
}

export interface RebootServerParams {
  /** Prim server ID. */
  id: string;
}

export interface ResizeServerParams {
  /** Prim server ID. */
  id: string;
}

export interface RebuildServerParams {
  /** Prim server ID. */
  id: string;
}

export interface DeleteSshKeyParams {
  /** Prim SSH key ID. */
  id: string;
}

export interface CreateServerResponse {
  server: ServerResponse;
  action: ActionResponse;
  /** USDC amount charged for this server (decimal string). */
  deposit_charged: string;
  /** Remaining USDC deposit balance (decimal string). */
  deposit_remaining: string;
}

export interface ListServersResponse {
  servers: ServerResponse[];
  meta: {
    page: number;
    per_page: number;
    total: number;
  };
}

export interface DeleteServerResponse {
  /** Always `"deleted"`. */
  status: "deleted";
  /** USDC amount refunded to the wallet (decimal string). */
  deposit_refunded: string;
}

export interface StartServerResponse {
  action: ActionResponse;
}

export interface StopServerResponse {
  action: ActionResponse;
}

export interface RebootServerResponse {
  action: ActionResponse;
}

export interface ResizeServerResponse {
  action: ActionResponse;
  /** The target server type. */
  new_type: string;
  /** USDC deposit change (positive = charged, negative = refunded). */
  deposit_delta: string;
}

export interface RebuildServerResponse {
  action: ActionResponse;
  /** New root password if no SSH keys are configured, otherwise null. */
  root_password: string | null;
}

export interface ListSshKeysResponse {
  ssh_keys: SshKeyResponse[];
}

export type DeleteSshKeyResponse = Record<string, unknown>;

// ── Client ─────────────────────────────────────────────────────────────────

export function createSpawnClient(
  primFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
) {
  const baseUrl = "https://spawn.prim.sh";
  return {
    async createServer(req: CreateServerRequest): Promise<CreateServerResponse> {
      const url = `${baseUrl}/v1/servers`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<CreateServerResponse>;
    },
    async listServers(params: ListServersParams): Promise<ListServersResponse> {
      const qs = new URLSearchParams();
      if (params.limit !== undefined) qs.set("limit", String(params.limit));
      if (params.page !== undefined) qs.set("page", String(params.page));
      const query = qs.toString();
      const url = `${baseUrl}/v1/servers${query ? `?${query}` : ""}`;
      const res = await primFetch(url);
      return res.json() as Promise<ListServersResponse>;
    },
    async getServer(params: GetServerParams): Promise<ServerResponse> {
      const url = `${baseUrl}/v1/servers/${encodeURIComponent(params.id)}`;
      const res = await primFetch(url);
      return res.json() as Promise<ServerResponse>;
    },
    async deleteServer(params: DeleteServerParams): Promise<DeleteServerResponse> {
      const url = `${baseUrl}/v1/servers/${encodeURIComponent(params.id)}`;
      const res = await primFetch(url, {
        method: "DELETE",
      });
      return res.json() as Promise<DeleteServerResponse>;
    },
    async startServer(params: StartServerParams): Promise<StartServerResponse> {
      const url = `${baseUrl}/v1/servers/${encodeURIComponent(params.id)}/start`;
      const res = await primFetch(url, {
        method: "POST",
      });
      return res.json() as Promise<StartServerResponse>;
    },
    async stopServer(params: StopServerParams): Promise<StopServerResponse> {
      const url = `${baseUrl}/v1/servers/${encodeURIComponent(params.id)}/stop`;
      const res = await primFetch(url, {
        method: "POST",
      });
      return res.json() as Promise<StopServerResponse>;
    },
    async rebootServer(params: RebootServerParams): Promise<RebootServerResponse> {
      const url = `${baseUrl}/v1/servers/${encodeURIComponent(params.id)}/reboot`;
      const res = await primFetch(url, {
        method: "POST",
      });
      return res.json() as Promise<RebootServerResponse>;
    },
    async resizeServer(
      params: ResizeServerParams,
      req: ResizeServerRequest,
    ): Promise<ResizeServerResponse> {
      const url = `${baseUrl}/v1/servers/${encodeURIComponent(params.id)}/resize`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<ResizeServerResponse>;
    },
    async rebuildServer(
      params: RebuildServerParams,
      req: RebuildServerRequest,
    ): Promise<RebuildServerResponse> {
      const url = `${baseUrl}/v1/servers/${encodeURIComponent(params.id)}/rebuild`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<RebuildServerResponse>;
    },
    async createSshKey(req: CreateSshKeyRequest): Promise<SshKeyResponse> {
      const url = `${baseUrl}/v1/ssh-keys`;
      const res = await primFetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(req),
      });
      return res.json() as Promise<SshKeyResponse>;
    },
    async listSshKeys(): Promise<ListSshKeysResponse> {
      const url = `${baseUrl}/v1/ssh-keys`;
      const res = await primFetch(url);
      return res.json() as Promise<ListSshKeysResponse>;
    },
    async deleteSshKey(params: DeleteSshKeyParams): Promise<DeleteSshKeyResponse> {
      const url = `${baseUrl}/v1/ssh-keys/${encodeURIComponent(params.id)}`;
      const res = await primFetch(url, {
        method: "DELETE",
      });
      return res.json() as Promise<DeleteSshKeyResponse>;
    },
  };
}
