name: Bug Report
description: Report a bug in a Prim primitive
labels: ["bug"]
body:
  - type: dropdown
    id: primitive
    attributes:
      label: Primitive
      description: Which primitive is affected?
      options:
        - wallet.sh
        - store.sh
        - spawn.sh
        - faucet.sh
        - email.sh
        - domain.sh
        - search.sh
        - token.sh
        - mem.sh
        - prim CLI
        - x402-middleware
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: "Curl commands, CLI invocations, or code snippets."
      render: bash
  - type: input
    id: network
    attributes:
      label: Network
      description: "e.g., Base Sepolia (eip155:84532) or Base Mainnet (eip155:8453)"
      placeholder: "eip155:84532"
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Error messages, response bodies, transaction hashes, etc.
