name: Feature Request
description: Suggest a feature or improvement
labels: ["enhancement"]
body:
  - type: dropdown
    id: primitive
    attributes:
      label: Primitive
      description: Which primitive does this relate to?
      options:
        - wallet.sh
        - store.sh
        - spawn.sh
        - faucet.sh
        - email.sh
        - domain.sh
        - search.sh
        - token.sh
        - mem.sh
        - prim CLI
        - New primitive
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What are you trying to do? Why is current behavior insufficient?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? Include endpoint designs, CLI usage, etc.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about.
