#!/usr/bin/env bun
/**
 * gen-costs.ts — Cost transparency page generator
 *
 * Reads docs/costs.yaml (infrastructure) + packages/star/prim.yaml (provider costs + prices),
 * joins them, computes margins, and outputs:
 *   - docs/costs.md (markdown summary)
 *   - site/docs/costs/index.html (public page)
 *
 * Usage:
 *   bun scripts/gen-costs.ts          # regenerate
 *   bun scripts/gen-costs.ts --check  # diff against disk, exit 1 if stale
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse as parseYaml } from "yaml";
import { type PricingRow, loadPrimitives } from "./lib/primitives.js";

const ROOT = resolve(import.meta.dir, "..");
const CHECK_MODE = process.argv.includes("--check");

// ── Types ──────────────────────────────────────────────────────────────────

interface InfraItem {
	item: string;
	provider: string;
	monthly_usd: number | null;
	billing: string;
	notes?: string;
}

interface RiskFlag {
	primitive: string;
	endpoint: string;
	severity: string;
	description: string;
}

interface CostsYaml {
	infrastructure: InfraItem[];
	risk_flags?: RiskFlag[];
}

// ── Helpers ────────────────────────────────────────────────────────────────

function parseUsd(s: string | undefined): number | null {
	if (!s) return null;
	const m = s.match(/^\$?([\d.]+)/);
	return m ? Number.parseFloat(m[1]) : null;
}

function computeMargin(price: number, cost: number): string {
	if (price === 0) return cost === 0 ? "—" : `-∞`;
	const pct = ((price - cost) / price) * 100;
	return `${pct >= 0 ? "" : ""}${Math.round(pct)}%`;
}

function applyOrCheck(filePath: string, content: string): void {
	const existing = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
	const changed = existing !== content;
	if (CHECK_MODE) {
		if (changed) {
			console.error(`  ✗ ${filePath} is out of date — run pnpm gen:costs`);
			process.exitCode = 1;
		} else {
			console.log(`  ✓ ${filePath}`);
		}
	} else {
		const dir = filePath.replace(/\/[^/]+$/, "");
		if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
		writeFileSync(filePath, content);
		console.log(`  ${changed ? "↺" : "✓"} ${filePath}`);
	}
}

// ── Load data ──────────────────────────────────────────────────────────────

const costsPath = resolve(ROOT, "docs/costs.yaml");
if (!existsSync(costsPath)) {
	console.error("docs/costs.yaml not found");
	process.exit(1);
}
const costs = parseYaml(readFileSync(costsPath, "utf8")) as CostsYaml;
const prims = loadPrimitives(ROOT);

// ── Compute ────────────────────────────────────────────────────────────────

const fixedTotal = costs.infrastructure.reduce((sum, i) => sum + (i.monthly_usd ?? 0), 0);

interface PrimCostRow {
	name: string;
	status: string;
	ops: {
		op: string;
		price: string;
		providerCost: string;
		margin: string;
	}[];
}

const primCosts: PrimCostRow[] = [];

for (const p of prims) {
	if (!p.pricing || p.pricing.length === 0) continue;
	const ops = p.pricing.map((r: PricingRow) => {
		const price = parseUsd(r.price);
		const cost = parseUsd(r.provider_cost);
		const margin =
			price !== null && cost !== null ? computeMargin(price, cost) : "—";
		return {
			op: r.op,
			price: r.price,
			providerCost: r.provider_cost ?? "—",
			margin,
		};
	});
	primCosts.push({
		name: p.name,
		status: p.status ?? "—",
		ops,
	});
}

// ── Render markdown ────────────────────────────────────────────────────────

function renderMarkdown(): string {
	const lines: string[] = [];
	lines.push("<!-- Generated by scripts/gen-costs.ts — do not edit -->");
	lines.push("# What it costs to run prim.sh");
	lines.push("");
	lines.push("Full cost transparency. Infrastructure costs are shared overhead;");
	lines.push("per-route provider costs live in each primitive's `prim.yaml`.");
	lines.push("");

	// Infrastructure
	lines.push("## Infrastructure");
	lines.push("");
	lines.push("| Item | Provider | Monthly | Notes |");
	lines.push("|------|----------|---------|-------|");
	for (const i of costs.infrastructure) {
		const monthly = i.monthly_usd !== null ? `$${i.monthly_usd.toFixed(2)}` : "variable";
		lines.push(`| ${i.item} | ${i.provider} | ${monthly} | ${i.notes ?? ""} |`);
	}
	lines.push(`| **Total fixed** | | **$${fixedTotal.toFixed(2)}/mo** | |`);
	lines.push("");

	// Per-primitive margins
	lines.push("## Per-primitive margins");
	lines.push("");
	for (const p of primCosts) {
		lines.push(`### ${p.name} (${p.status})`);
		lines.push("");
		lines.push("| Operation | Price | Provider Cost | Margin |");
		lines.push("|-----------|-------|---------------|--------|");
		for (const op of p.ops) {
			lines.push(`| ${op.op} | ${op.price} | ${op.providerCost} | ${op.margin} |`);
		}
		lines.push("");
	}

	// Risk flags
	if (costs.risk_flags && costs.risk_flags.length > 0) {
		lines.push("## Risk flags");
		lines.push("");
		lines.push("| Primitive | Endpoint | Severity | Description |");
		lines.push("|-----------|----------|----------|-------------|");
		for (const r of costs.risk_flags) {
			lines.push(`| ${r.primitive} | ${r.endpoint} | ${r.severity} | ${r.description} |`);
		}
		lines.push("");
	}

	return `${lines.join("\n")}\n`;
}

// ── Render HTML ────────────────────────────────────────────────────────────

function renderHtml(): string {
	const infraRows = costs.infrastructure
		.map((i) => {
			const monthly = i.monthly_usd !== null ? `$${i.monthly_usd.toFixed(2)}` : "variable";
			return `          <tr><td>${i.item}</td><td>${i.provider}</td><td>${monthly}</td><td class="muted">${i.notes ?? ""}</td></tr>`;
		})
		.join("\n");

	const primSections = primCosts
		.map((p) => {
			const rows = p.ops
				.map((op) => {
					const marginClass = op.margin.startsWith("-") ? "r" : "g";
					return `          <tr><td>${op.op}</td><td>${op.price}</td><td>${op.providerCost}</td><td class="${marginClass}">${op.margin}</td></tr>`;
				})
				.join("\n");
			return `
      <h3>${p.name} <span class="muted">(${p.status})</span></h3>
      <table>
        <thead>
          <tr><th>Operation</th><th>Price</th><th>Provider Cost</th><th>Margin</th></tr>
        </thead>
        <tbody>
${rows}
        </tbody>
      </table>`;
		})
		.join("\n");

	const riskRows = (costs.risk_flags ?? [])
		.map(
			(r) =>
				`          <tr><td>${r.primitive}</td><td class="muted">${r.endpoint}</td><td class="${r.severity === "high" ? "r" : "y"}">${r.severity}</td><td>${r.description}</td></tr>`,
		)
		.join("\n");

	return `<!DOCTYPE html>
<!-- Generated by scripts/gen-costs.ts — do not edit -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Costs — prim.sh</title>
  <style>
    :root { --bg: #0a0a0a; --surface: #111; --text: #e0e0e0; --muted: #666; --accent: #00ff88; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: var(--bg); color: var(--text); font-family: 'SF Mono', SFMono-Regular, 'Cascadia Code', Consolas, monospace; font-size: 14px; line-height: 1.6; padding: 2rem; max-width: 900px; margin: 0 auto; }
    h1 { color: var(--accent); font-size: 1.5rem; margin-bottom: 0.5rem; }
    h2 { color: var(--text); font-size: 1.1rem; margin-top: 2rem; margin-bottom: 0.75rem; border-bottom: 1px solid #222; padding-bottom: 0.25rem; }
    h3 { color: var(--text); font-size: 0.95rem; margin-top: 1.5rem; margin-bottom: 0.5rem; }
    p { color: var(--muted); margin-bottom: 1rem; }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 1rem; font-size: 13px; }
    th, td { text-align: left; padding: 0.4rem 0.75rem; border-bottom: 1px solid #1a1a1a; }
    th { color: var(--muted); font-weight: normal; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
    tr:hover { background: var(--surface); }
    .total td { font-weight: bold; border-top: 2px solid #333; }
    .muted { color: var(--muted); }
    .g { color: #00ff88; }
    .r { color: #ff4444; }
    .y { color: #ffcc00; }
    .back { display: inline-block; margin-bottom: 1.5rem; color: var(--muted); font-size: 13px; }
    .back:hover { color: var(--accent); }
    .updated { color: var(--muted); font-size: 12px; margin-top: 2rem; }
  </style>
</head>
<body>
  <a href="/" class="back">← prim.sh</a>
  <h1>What it costs to run prim.sh</h1>
  <p>Full cost transparency. Infrastructure costs are shared overhead; per-route provider costs live in each primitive's prim.yaml.</p>

  <h2>Infrastructure</h2>
  <table>
    <thead>
      <tr><th>Item</th><th>Provider</th><th>Monthly</th><th>Notes</th></tr>
    </thead>
    <tbody>
${infraRows}
    </tbody>
    <tfoot>
      <tr class="total"><td>Total fixed</td><td></td><td>$${fixedTotal.toFixed(2)}/mo</td><td></td></tr>
    </tfoot>
  </table>

  <h2>Per-primitive margins</h2>
${primSections}

  <h2>Risk flags</h2>
  <table>
    <thead>
      <tr><th>Primitive</th><th>Endpoint</th><th>Severity</th><th>Description</th></tr>
    </thead>
    <tbody>
${riskRows}
    </tbody>
  </table>

  <p class="updated">Generated from <a href="https://github.com/primsh/prim.sh/blob/main/docs/costs.yaml">docs/costs.yaml</a> + prim.yaml files.</p>
</body>
</html>
`;
}

// ── Write ──────────────────────────────────────────────────────────────────

console.log(CHECK_MODE ? "Mode: check\n" : "Mode: generate\n");

applyOrCheck(resolve(ROOT, "docs/costs.md"), renderMarkdown());
applyOrCheck(resolve(ROOT, "site/docs/costs/index.html"), renderHtml());

if (CHECK_MODE && process.exitCode) {
	console.error("\nCost files are out of date. Run: pnpm gen:costs");
} else if (CHECK_MODE) {
	console.log("\nAll cost files are up to date.");
} else {
	console.log("\nDone.");
}
