#!/usr/bin/env bun
/**
 * gen-openapi.ts — OpenAPI spec generator
 *
 * Reads prim.yaml + api.ts for each eligible primitive, generates OpenAPI 3.1 specs
 * colocated at packages/<id>/openapi.yaml.
 *
 * Usage:
 *   bun scripts/gen-openapi.ts                # generate specs for new/generated prims
 *   bun scripts/gen-openapi.ts --check        # diff against disk, exit 1 if stale
 *   bun scripts/gen-openapi.ts --force        # regenerate all eligible prims (overwrite existing)
 *   bun scripts/gen-openapi.ts track          # generate for a single prim
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { parseApiFile } from "./lib/parse-api.js";
import { loadPrimitives, specPath, withPackage } from "./lib/primitives.js";
import { parseRoutePrices } from "./lib/render-llms-txt.js";
import { renderOpenApi } from "./lib/render-openapi.js";

const ROOT = resolve(import.meta.dir, "..");
const GENERATED_MARKER = "# Generated by gen:openapi";

const args = process.argv.slice(2);
const CHECK_MODE = args.includes("--check");
const FORCE = args.includes("--force");
const primIdArg = args.find((a) => !a.startsWith("-")) ?? null;

let anyFailed = false;

function isGenerated(filePath: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, "utf8");
  return content.startsWith(GENERATED_MARKER) || content.startsWith("# THIS FILE IS GENERATED");
}

function applyFullFile(filePath: string, content: string): void {
  const existing = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
  const changed = existing !== content;
  if (CHECK_MODE) {
    if (changed) {
      console.error(`  ✗ ${filePath} is out of date — run pnpm gen:openapi`);
      anyFailed = true;
    } else {
      console.log(`  ✓ ${filePath}`);
    }
  } else {
    writeFileSync(filePath, content);
    console.log(`  ${changed ? "↺" : "✓"} ${filePath}`);
  }
}

// ── Main ───────────────────────────────────────────────────────────────────

const prims = loadPrimitives();
const packaged = withPackage(prims, ROOT);

// Filter to eligible prims: has routes_map + has api.ts + (no existing spec OR generated by us OR --force)
let eligible = packaged.filter((p) => {
  if (!p.routes_map || p.routes_map.length === 0) return false;
  if (!existsSync(join(ROOT, "packages", p.id, "src/api.ts"))) return false;
  if (FORCE) return true;
  const sp = specPath(p.id);
  return !existsSync(sp) || isGenerated(sp);
});

if (primIdArg) {
  eligible = eligible.filter((p) => p.id === primIdArg);
}

const skipped = packaged.filter((p) => {
  if (!p.routes_map || p.routes_map.length === 0) return false;
  if (!existsSync(join(ROOT, "packages", p.id, "src/api.ts"))) return false;
  const sp = specPath(p.id);
  return existsSync(sp) && !isGenerated(sp) && !FORCE;
});

console.log(`Eligible: ${eligible.length} prims${FORCE ? " (force mode)" : ""}`);
if (skipped.length > 0) {
  console.log(`Skipped (hand-written specs): ${skipped.map((p) => p.id).join(", ")}`);
}
console.log(CHECK_MODE ? "Mode: check\n" : "Mode: generate\n");

for (const p of eligible) {
  const apiPath = join(ROOT, "packages", p.id, "src/api.ts");
  const indexPath = join(ROOT, "packages", p.id, "src/index.ts");
  const outPath = specPath(p.id);

  const api = parseApiFile(apiPath);
  const prices = existsSync(indexPath) ? parseRoutePrices(indexPath) : new Map<string, string>();

  const specYaml = renderOpenApi(p, api, prices);
  const header = `${GENERATED_MARKER}\n# THIS FILE IS GENERATED — DO NOT EDIT\n# Source: packages/${p.id}/prim.yaml + packages/${p.id}/src/api.ts\n# Regenerate: pnpm gen:openapi\n\n`;
  applyFullFile(outPath, header + specYaml);
}

// ── Exit ───────────────────────────────────────────────────────────────────

if (CHECK_MODE && anyFailed) {
  console.error("\nSome files are out of date. Run: pnpm gen:openapi");
  process.exit(1);
} else if (CHECK_MODE) {
  console.log("\nAll generated files are up to date.");
} else {
  console.log("\nDone.");
}
