#!/usr/bin/env bun
/**
 * gen-costs.ts — Cost transparency page generator
 *
 * Reads docs/costs.yaml (infrastructure) + each package's prim.yaml (provider costs + prices),
 * joins them, and outputs:
 *   - docs/costs.md (markdown summary)
 *   - site/docs/costs/index.html (public page)
 *
 * Usage:
 *   bun scripts/gen-costs.ts          # regenerate
 *   bun scripts/gen-costs.ts --check  # diff against disk, exit 1 if stale
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse as parseYaml } from "yaml";
import { type PricingRow, loadPrimitives } from "./lib/primitives.js";

const ROOT = resolve(import.meta.dir, "..");
const CHECK_MODE = process.argv.includes("--check");

// ── Types ──────────────────────────────────────────────────────────────────

interface InfraItem {
	item: string;
	provider: string;
	monthly_usd: number | null;
	billing: string;
	reason?: string;
	as_of?: string;
}

interface CostsYaml {
	infrastructure: InfraItem[];
}

// ── Helpers ────────────────────────────────────────────────────────────────

function applyOrCheck(filePath: string, content: string): void {
	const existing = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
	const changed = existing !== content;
	if (CHECK_MODE) {
		if (changed) {
			console.error(`  ✗ ${filePath} is out of date — run pnpm gen:costs`);
			process.exitCode = 1;
		} else {
			console.log(`  ✓ ${filePath}`);
		}
	} else {
		const dir = filePath.replace(/\/[^/]+$/, "");
		if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
		writeFileSync(filePath, content);
		console.log(`  ${changed ? "↺" : "✓"} ${filePath}`);
	}
}

function typeBadge(r: PricingRow): string {
	return r.pricing_type === "dynamic" ? "dynamic" : "static";
}

function priceDisplay(r: PricingRow): string {
	if (r.price === "free") return "free";
	if (r.price === "dynamic") return r.estimate ? `~${r.estimate}` : "dynamic";
	if (r.pricing_type === "dynamic" && r.estimate) return `${r.price} (varies)`;
	return r.price;
}

// ── Load data ──────────────────────────────────────────────────────────────

const costsPath = resolve(ROOT, "docs/costs.yaml");
if (!existsSync(costsPath)) {
	console.error("docs/costs.yaml not found");
	process.exit(1);
}
const costs = parseYaml(readFileSync(costsPath, "utf8")) as CostsYaml;
const prims = loadPrimitives(ROOT);

// ── Compute ────────────────────────────────────────────────────────────────

const fixedTotal = costs.infrastructure.reduce((sum, i) => sum + (i.monthly_usd ?? 0), 0);

interface PrimCostRow {
	name: string;
	status: string;
	ops: {
		op: string;
		price: string;
		providerCost: string;
		type: string;
		verified: string;
	}[];
}

const primCosts: PrimCostRow[] = [];

for (const p of prims) {
	if (!p.pricing || p.pricing.length === 0) continue;
	const ops = p.pricing.map((r: PricingRow) => ({
		op: r.op,
		price: priceDisplay(r),
		providerCost: r.provider_cost ?? "—",
		type: typeBadge(r),
		verified: r.as_of ?? "—",
	}));
	primCosts.push({
		name: p.name,
		status: p.status ?? "—",
		ops,
	});
}

// ── Render markdown ────────────────────────────────────────────────────────

function renderMarkdown(): string {
	const lines: string[] = [];
	lines.push("<!-- Generated by scripts/gen-costs.ts — do not edit -->");
	lines.push("# What it costs to run prim.sh");
	lines.push("");
	lines.push("At-cost pricing. Zero margin. Pay for what you use.");
	lines.push("Fixed infrastructure ($24.49/mo) is absorbed by the business.");
	lines.push("");

	// Infrastructure
	lines.push("## Infrastructure");
	lines.push("");
	lines.push("| Item | Provider | Monthly | What & Why |");
	lines.push("|------|----------|---------|------------|");
	for (const i of costs.infrastructure) {
		const monthly = i.monthly_usd !== null ? `$${i.monthly_usd.toFixed(2)}` : "variable";
		lines.push(`| ${i.item} | ${i.provider} | ${monthly} | ${i.reason ?? ""} |`);
	}
	lines.push(`| **Total fixed** | | **$${fixedTotal.toFixed(2)}/mo** | |`);
	lines.push("");

	// Per-primitive costs
	lines.push("## Per-primitive costs");
	lines.push("");
	for (const p of primCosts) {
		lines.push(`### ${p.name} (${p.status})`);
		lines.push("");
		lines.push("| Operation | Price | Provider Cost | Type | Verified |");
		lines.push("|-----------|-------|---------------|------|----------|");
		for (const op of p.ops) {
			lines.push(`| ${op.op} | ${op.price} | ${op.providerCost} | ${op.type} | ${op.verified} |`);
		}
		lines.push("");
	}

	return `${lines.join("\n")}\n`;
}

// ── Render HTML ────────────────────────────────────────────────────────────

function renderHtml(): string {
	const infraRows = costs.infrastructure
		.map((i) => {
			const monthly = i.monthly_usd !== null ? `$${i.monthly_usd.toFixed(2)}` : "variable";
			return `          <tr><td>${i.item}</td><td>${i.provider}</td><td>${monthly}</td><td class="muted">${i.reason ?? ""}</td></tr>`;
		})
		.join("\n");

	const primSections = primCosts
		.map((p) => {
			const rows = p.ops
				.map((op) => {
					const isFree = op.price === "free";
					const badgeClass = op.type === "dynamic" ? "badge badge-dynamic" : "badge badge-static";
					const priceClass = isFree ? "free" : "";
					return `          <tr><td>${op.op}</td><td class="${priceClass}">${op.price}</td><td>${op.providerCost}</td><td><span class="${badgeClass}">${op.type}</span></td><td class="muted">${op.verified}</td></tr>`;
				})
				.join("\n");
			return `
      <h3>${p.name} <span class="muted">(${p.status})</span></h3>
      <table>
        <thead>
          <tr><th>Operation</th><th>Price</th><th>Provider Cost</th><th>Type</th><th>Verified</th></tr>
        </thead>
        <tbody>
${rows}
        </tbody>
      </table>`;
		})
		.join("\n");

	return `<!DOCTYPE html>
<!-- Generated by scripts/gen-costs.ts — do not edit -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Costs — prim.sh</title>
  <style>
    :root { --bg: #0a0a0a; --surface: #111; --text: #e0e0e0; --muted: #666; --accent: #00ff88; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: var(--bg); color: var(--text); font-family: 'SF Mono', SFMono-Regular, 'Cascadia Code', Consolas, monospace; font-size: 14px; line-height: 1.6; padding: 2rem; max-width: 900px; margin: 0 auto; }
    h1 { color: var(--accent); font-size: 1.5rem; margin-bottom: 0.5rem; }
    h2 { color: var(--text); font-size: 1.1rem; margin-top: 2rem; margin-bottom: 0.75rem; border-bottom: 1px solid #222; padding-bottom: 0.25rem; }
    h3 { color: var(--text); font-size: 0.95rem; margin-top: 1.5rem; margin-bottom: 0.5rem; }
    p { color: var(--muted); margin-bottom: 1rem; }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 1rem; font-size: 13px; }
    th, td { text-align: left; padding: 0.4rem 0.75rem; border-bottom: 1px solid #1a1a1a; }
    th { color: var(--muted); font-weight: normal; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
    tr:hover { background: var(--surface); }
    .total td { font-weight: bold; border-top: 2px solid #333; }
    .muted { color: var(--muted); }
    .g { color: #00ff88; }
    .r { color: #ff4444; }
    .y { color: #ffcc00; }
    .free { color: #00ff88; }
    .badge { display: inline-block; padding: 0.1rem 0.4rem; border-radius: 3px; font-size: 11px; font-weight: bold; letter-spacing: 0.03em; }
    .badge-static { background: #1a2e1a; color: #00ff88; }
    .badge-dynamic { background: #2e2a1a; color: #ffcc00; }
    .back { display: inline-block; margin-bottom: 1.5rem; color: var(--muted); font-size: 13px; }
    .back:hover { color: var(--accent); }
    .updated { color: var(--muted); font-size: 12px; margin-top: 2rem; }
  </style>
</head>
<body>
  <a href="/" class="back">← prim.sh</a>
  <h1>What it costs to run prim.sh</h1>
  <p>At-cost pricing. Zero margin. Pay for what you use. Fixed infrastructure ($${fixedTotal.toFixed(2)}/mo) is absorbed by the business.</p>

  <h2>Infrastructure</h2>
  <table>
    <thead>
      <tr><th>Item</th><th>Provider</th><th>Monthly</th><th>What &amp; Why</th></tr>
    </thead>
    <tbody>
${infraRows}
    </tbody>
    <tfoot>
      <tr class="total"><td>Total fixed</td><td></td><td>$${fixedTotal.toFixed(2)}/mo</td><td></td></tr>
    </tfoot>
  </table>

  <h2>Per-primitive costs</h2>
${primSections}

  <p class="updated">Generated from <a href="https://github.com/primsh/prim.sh/blob/main/docs/costs.yaml">docs/costs.yaml</a> + prim.yaml files.</p>
</body>
</html>
`;
}

// ── Write ──────────────────────────────────────────────────────────────────

console.log(CHECK_MODE ? "Mode: check\n" : "Mode: generate\n");

applyOrCheck(resolve(ROOT, "docs/costs.md"), renderMarkdown());
applyOrCheck(resolve(ROOT, "site/docs/costs/index.html"), renderHtml());

if (CHECK_MODE && process.exitCode) {
	console.error("\nCost files are out of date. Run: pnpm gen:costs");
} else if (CHECK_MODE) {
	console.log("\nAll cost files are up to date.");
} else {
	console.log("\nDone.");
}
