#!/usr/bin/env bun
/**
 * gen-status.ts — Status page generator
 *
 * Reads each package's prim.yaml status + primitives.yaml for phantoms,
 * and outputs:
 *   - site/status/index.html (public page)
 *
 * Usage:
 *   bun scripts/gen-status.ts          # regenerate
 *   bun scripts/gen-status.ts --check  # diff against disk, exit 1 if stale
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { BRAND } from "../site/brand.ts";
import { renderFooter } from "../site/template.ts";
import { loadPrimitives } from "./lib/primitives.js";

const ROOT = resolve(import.meta.dir, "..");
const CHECK_MODE = process.argv.includes("--check");

// ── Helpers ────────────────────────────────────────────────────────────────

function applyOrCheck(filePath: string, content: string): void {
	const existing = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
	const changed = existing !== content;
	if (CHECK_MODE) {
		if (changed) {
			console.error(`  ✗ ${filePath} is out of date — run pnpm gen:status`);
			process.exitCode = 1;
		} else {
			console.log(`  ✓ ${filePath}`);
		}
	} else {
		const dir = filePath.replace(/\/[^/]+$/, "");
		if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
		writeFileSync(filePath, content);
		console.log(`  ${changed ? "↺" : "✓"} ${filePath}`);
	}
}

// ── Load data ──────────────────────────────────────────────────────────────

const prims = loadPrimitives(ROOT);

interface StatusRow {
	name: string;
	id: string;
	endpoint: string;
	description: string;
	status: string;
	category: string;
}

const rows: StatusRow[] = prims.map((p) => ({
	name: p.name,
	id: p.id,
	endpoint: p.endpoint ?? `${p.id}.prim.sh`,
	description: p.description ?? "",
	status: p.status ?? "hold",
	category: p.category ?? "meta",
}));

const live = rows.filter((r) => r.status === "mainnet" || r.status === "testnet");
const hold = rows.filter((r) => r.status === "hold");

// ── Render HTML ────────────────────────────────────────────────────────────

function statusDot(status: string): string {
	switch (status) {
		case "mainnet":
		case "testnet":
			return '<span class="dot dot-live">●</span>';
		default:
			return '<span class="dot dot-hold">○</span>';
	}
}

function statusLabel(status: string): string {
	switch (status) {
		case "mainnet":
			return "mainnet";
		case "testnet":
			return "testnet";
		default:
			return "";
	}
}

function renderRow(r: StatusRow): string {
	const isLive = r.status === "mainnet" || r.status === "testnet";
	const endpoint = isLive
		? `<a href="https://${r.endpoint}">${r.endpoint}</a>`
		: `<span class="muted">${r.endpoint}</span>`;
	const nameLink = isLive
		? `<a href="/${r.id}">${r.name}</a>`
		: `<span>${r.name}</span>`;
	const label = statusLabel(r.status);
	const labelHtml = label ? ` <span class="net-label">${label}</span>` : "";
	return `      <tr>
        <td>${statusDot(r.status)}</td>
        <td>${nameLink}${labelHtml}</td>
        <td>${endpoint}</td>
        <td class="muted">${r.description}</td>
      </tr>`;
}

function renderSection(title: string, _label: string, items: StatusRow[]): string {
	if (items.length === 0) return "";
	const rowsHtml = items.map(renderRow).join("\n");
	return `
<h2>${title} <span class="count">${items.length}</span></h2>
<table>
  <thead>
    <tr><th></th><th>Service</th><th>Endpoint</th><th>Description</th></tr>
  </thead>
  <tbody>
${rowsHtml}
  </tbody>
</table>`;
}

function renderHtml(): string {
	const liveSection = renderSection("Live", "live", live);
	const holdSection = renderSection("Coming soon", "hold", hold);

	const footer = renderFooter(`<a href="/">${BRAND.name}</a> / status`);

	return `<!DOCTYPE html>
<!-- Generated by scripts/gen-status.ts — do not edit -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Status — ${BRAND.name}</title>
<meta name="description" content="Live status of all ${BRAND.name} primitives. ${live.length} live, ${hold.length} coming soon.">
<meta name="theme-color" content="#0a0a0a">
<meta property="og:type" content="website">
<meta property="og:title" content="Status — ${BRAND.name}">
<meta property="og:description" content="Live status of all ${BRAND.name} primitives. ${live.length} live, ${hold.length} coming soon.">
<meta property="og:url" content="https://prim.sh/status">
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@primitiveshell">
<link rel="canonical" href="https://prim.sh/status">
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg">
<link rel="icon" type="image/png" href="/assets/favicon-192.png">
<link rel="apple-touch-icon" href="/assets/favicon-180.png">
<link rel="stylesheet" href="/assets/prim.css">
<style>
.status-wrap{max-width:900px;margin:0 auto;padding:2rem}
.status-wrap h2{color:var(--text);font-size:1.1rem;margin-top:2rem;margin-bottom:0.75rem;border-bottom:1px solid var(--border);padding-bottom:0.25rem}
.status-wrap .count{color:var(--muted);font-weight:normal;font-size:0.85rem}
.status-wrap p{color:var(--muted);margin-bottom:1rem;font-size:0.9rem}
.status-wrap table{width:100%;border-collapse:collapse;margin-bottom:1rem;font-size:13px}
.status-wrap th,.status-wrap td{text-align:left;padding:0.4rem 0.75rem;border-bottom:1px solid var(--border)}
.status-wrap th{color:var(--muted);font-weight:normal;font-size:12px;text-transform:uppercase;letter-spacing:0.05em}
.status-wrap tr:hover{background:var(--surface)}
.status-wrap .muted{color:var(--muted)}
.status-wrap a{color:var(--accent);text-decoration:none}
.status-wrap a:hover{text-decoration:underline}
.dot{font-size:10px;vertical-align:middle}
.dot-live{color:#00ff88}
.dot-hold{color:#444}
.net-label{color:var(--muted);font-size:11px;font-weight:normal;margin-left:0.3rem}
.status-wrap .discovery{margin-top:2rem;padding:1rem;background:var(--surface);border:1px solid var(--border);border-radius:6px;font-size:13px}
.status-wrap .discovery code{color:var(--accent)}
.status-wrap .updated{color:var(--muted);font-size:12px;margin-top:2rem}
</style>
</head>
<body>
<div class="hero">
  <img class="logomark" src="/assets/hero.jpg" alt=">|">
  <div class="hero-hd"><a href="/" class="pill"><span class="parent">${BRAND.name}</span><span class="sep">/</span><span class="child">status</span></a></div>
  <h1 class="logo"><span>status</span>.sh</h1>
  <div class="tagline" style="color:var(--muted);font-size:1.1rem;margin-bottom:0.5rem">${live.length} live. ${hold.length}&#x267E;&#xFE0F; coming.</div>
  <div class="tagline">All systems operational.</div>
</div>

<div class="status-wrap">
${liveSection}
${holdSection}

<div class="discovery">
  <strong>For agents:</strong> query <code>GET <a href="/discovery.json">prim.sh/discovery.json</a></code> for machine-readable status and endpoints, or <code>GET <a href="/pricing.json">prim.sh/pricing.json</a></code> for all route prices.
</div>

<p class="updated">Generated from prim.yaml files. See <a href="/costs">costs</a> for full pricing breakdown.</p>

</div>

${footer}
<img src="/assets/banner.jpg" alt="" class="img-fade" style="width:100%;display:block;margin:0;padding:0">
</body>
</html>
`;
}

// ── Write ──────────────────────────────────────────────────────────────────

console.log(CHECK_MODE ? "Mode: check\n" : "Mode: generate\n");

applyOrCheck(resolve(ROOT, "site/status/index.html"), renderHtml());

if (CHECK_MODE && process.exitCode) {
	console.error("\nStatus page is out of date. Run: pnpm gen:status");
} else if (CHECK_MODE) {
	console.log("\nStatus page is up to date.");
} else {
	console.log("\nDone.");
}
