#!/usr/bin/env bun
/**
 * gen-costs.ts — Cost transparency page generator
 *
 * Reads docs/costs.yaml (infrastructure) + each package's prim.yaml (provider costs + prices),
 * joins them, and outputs:
 *   - docs/costs.md (markdown summary)
 *   - site/costs/index.html (public page)
 *
 * Usage:
 *   bun scripts/gen-costs.ts          # regenerate
 *   bun scripts/gen-costs.ts --check  # diff against disk, exit 1 if stale
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse as parseYaml } from "yaml";
import { BRAND } from "../site/brand.ts";
import { renderFooter } from "../site/template.ts";
import { type PricingRow, loadPrimitives } from "./lib/primitives.js";

const ROOT = resolve(import.meta.dir, "..");
const CHECK_MODE = process.argv.includes("--check");

// ── Types ──────────────────────────────────────────────────────────────────

interface InfraItem {
	item: string;
	provider: string;
	monthly_usd: number | null;
	billing: string;
	reason?: string;
	as_of?: string;
}

interface CostsYaml {
	infrastructure: InfraItem[];
}

// ── Helpers ────────────────────────────────────────────────────────────────

function applyOrCheck(filePath: string, content: string): void {
	const existing = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
	const changed = existing !== content;
	if (CHECK_MODE) {
		if (changed) {
			console.error(`  ✗ ${filePath} is out of date — run pnpm gen:costs`);
			process.exitCode = 1;
		} else {
			console.log(`  ✓ ${filePath}`);
		}
	} else {
		const dir = filePath.replace(/\/[^/]+$/, "");
		if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
		writeFileSync(filePath, content);
		console.log(`  ${changed ? "↺" : "✓"} ${filePath}`);
	}
}

function typeBadge(r: PricingRow): string {
	return r.pricing_type === "dynamic" ? "dynamic" : "static";
}

function priceDisplay(r: PricingRow): string {
	if (r.price === "free") return "free";
	if (r.price === "dynamic") return r.estimate ? `~${r.estimate}` : "dynamic";
	if (r.pricing_type === "dynamic" && r.estimate) return `${r.price} (varies)`;
	return r.price;
}

// ── Load data ──────────────────────────────────────────────────────────────

const costsPath = resolve(ROOT, "docs/costs.yaml");
if (!existsSync(costsPath)) {
	console.error("docs/costs.yaml not found");
	process.exit(1);
}
const costs = parseYaml(readFileSync(costsPath, "utf8")) as CostsYaml;
const prims = loadPrimitives(ROOT);

// ── Compute ────────────────────────────────────────────────────────────────

const fixedTotal = costs.infrastructure.reduce((sum, i) => sum + (i.monthly_usd ?? 0), 0);

interface PrimCostRow {
	name: string;
	status: string;
	ops: {
		op: string;
		price: string;
		providerCost: string;
		type: string;
		verified: string;
	}[];
}

const primCosts: PrimCostRow[] = [];

for (const p of prims) {
	if (!p.pricing || p.pricing.length === 0) continue;
	const ops = p.pricing.map((r: PricingRow) => ({
		op: r.op,
		price: priceDisplay(r),
		providerCost: r.provider_cost ?? "—",
		type: typeBadge(r),
		verified: r.as_of ?? "—",
	}));
	primCosts.push({
		name: p.name,
		status: p.status ?? "—",
		ops,
	});
}

// ── Render markdown ────────────────────────────────────────────────────────

function renderMarkdown(): string {
	const lines: string[] = [];
	lines.push("<!-- Generated by scripts/gen-costs.ts — do not edit -->");
	lines.push("# What it costs to run prim.sh");
	lines.push("");
	lines.push("At-cost\\* pricing. Zero margin. Pay for what you use.");
	lines.push(`Fixed infrastructure ($${fixedTotal.toFixed(2)}/mo) is absorbed by Primitive Shell.`);
	lines.push("");

	// Infrastructure
	lines.push("## Infrastructure");
	lines.push("");
	lines.push("| Item | Provider | Monthly | What & Why |");
	lines.push("|------|----------|---------|------------|");
	for (const i of costs.infrastructure) {
		const monthly = i.monthly_usd !== null ? `$${i.monthly_usd.toFixed(2)}` : "variable";
		lines.push(`| ${i.item} | ${i.provider} | ${monthly} | ${i.reason ?? ""} |`);
	}
	lines.push(`| **Total fixed** | | **$${fixedTotal.toFixed(2)}/mo** | |`);
	lines.push("");

	// Per-primitive costs
	lines.push("## Per-primitive costs");
	lines.push("");
	for (const p of primCosts) {
		lines.push(`### ${p.name} (${p.status})`);
		lines.push("");
		lines.push("| Operation | Price | Provider Cost | Type | Verified |");
		lines.push("|-----------|-------|---------------|------|----------|");
		for (const op of p.ops) {
			lines.push(`| ${op.op} | ${op.price} | ${op.providerCost} | ${op.type} | ${op.verified} |`);
		}
		lines.push("");
	}

	lines.push("---");
	lines.push("");
	lines.push("\\* Agents pay only the listed USDC price — no gas fees. x402 uses EIP-3009 meta-transactions: the agent signs off-chain, the facilitator submits the transaction and pays Base chain gas. Primitive Shell absorbs the facilitator settlement fee ($0.001/tx after the first 1,000/month). Operations priced at $0.001 (\"x402 floor\") are the minimum the protocol needs to identify the caller's wallet. This revenue covers protocol overhead (caller identification, ownership scoping, abuse prevention) — it is not a provider pass-through cost.");
	lines.push("");
	lines.push("Prices reflect current provider rates and may change. See [Terms of Service](https://prim.sh/terms) for details.");
	lines.push("");

	return `${lines.join("\n")}\n`;
}

// ── Render HTML ────────────────────────────────────────────────────────────

function renderHtml(): string {
	const infraRows = costs.infrastructure
		.map((i) => {
			const monthly = i.monthly_usd !== null ? `$${i.monthly_usd.toFixed(2)}` : "variable";
			return `      <tr><td>${i.item}</td><td>${i.provider}</td><td>${monthly}</td><td class="muted">${i.reason ?? ""}</td></tr>`;
		})
		.join("\n");

	const primSections = primCosts
		.map((p) => {
			const rows = p.ops
				.map((op) => {
					const isFree = op.price === "free";
					const badgeClass = op.type === "dynamic" ? "badge badge-dynamic" : "badge badge-static";
					const priceClass = isFree ? "free" : "";
					return `      <tr><td>${op.op}</td><td class="${priceClass}">${op.price}</td><td>${op.providerCost}</td><td><span class="${badgeClass}">${op.type}</span></td><td class="muted">${op.verified}</td></tr>`;
				})
				.join("\n");
			return `
<h3>${p.name} <span class="muted">(${p.status})</span></h3>
<table>
  <thead>
    <tr><th>Operation</th><th>Price</th><th>Provider Cost</th><th>Type</th><th>Verified</th></tr>
  </thead>
  <tbody>
${rows}
  </tbody>
</table>`;
		})
		.join("\n");

	const footer = renderFooter(`<a href="/">${BRAND.name}</a> / costs`);

	return `<!DOCTYPE html>
<!-- Generated by scripts/gen-costs.ts — do not edit -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Costs — ${BRAND.name}</title>
<meta name="description" content="At-cost pricing. Zero margin. Pay for what you use. Full cost breakdown for every prim.sh primitive.">
<meta name="theme-color" content="#0a0a0a">
<meta property="og:type" content="website">
<meta property="og:title" content="Costs — ${BRAND.name}">
<meta property="og:description" content="At-cost pricing. Zero margin. Pay for what you use. Full cost breakdown for every prim.sh primitive.">
<meta property="og:url" content="https://prim.sh/costs">
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@useprim">
<link rel="canonical" href="https://prim.sh/costs">
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg">
<link rel="icon" type="image/png" href="/assets/favicon-192.png">
<link rel="apple-touch-icon" href="/assets/favicon-180.png">
<link rel="stylesheet" href="/assets/prim.css">
<style>
.costs-wrap{max-width:900px;margin:0 auto;padding:2rem}
.costs-wrap h2{color:var(--text);font-size:1.1rem;margin-top:2rem;margin-bottom:0.75rem;border-bottom:1px solid var(--border);padding-bottom:0.25rem}
.costs-wrap h3{color:var(--text);font-size:0.95rem;margin-top:1.5rem;margin-bottom:0.5rem}
.costs-wrap p{color:var(--muted);margin-bottom:1rem;font-size:0.9rem}
.costs-wrap table{width:100%;border-collapse:collapse;margin-bottom:1rem;font-size:13px}
.costs-wrap th,.costs-wrap td{text-align:left;padding:0.4rem 0.75rem;border-bottom:1px solid var(--border)}
.costs-wrap th{color:var(--muted);font-weight:normal;font-size:12px;text-transform:uppercase;letter-spacing:0.05em}
.costs-wrap tr:hover{background:var(--surface)}
.costs-wrap .total td{font-weight:bold;border-top:2px solid #333}
.costs-wrap .muted{color:var(--muted)}
.costs-wrap .free{color:var(--accent)}
.costs-wrap .badge{display:inline-block;padding:0.1rem 0.4rem;border-radius:3px;font-size:11px;font-weight:bold;letter-spacing:0.03em}
.costs-wrap .badge-static{background:#1a2e1a;color:var(--accent)}
.costs-wrap .badge-dynamic{background:#2e2a1a;color:#ffcc00}
.costs-wrap .updated{color:var(--muted);font-size:12px;margin-top:2rem}
</style>
</head>
<body>
<div class="hero">
  <img class="logomark" src="/assets/hero.jpg" alt=">|">
  <div class="hero-hd"><a href="/" class="pill"><span class="parent">${BRAND.name}</span><span class="sep">/</span><span class="child">costs</span></a></div>
  <h1 class="logo">What it <span>costs</span></h1>
  <div class="tagline">At-cost<a href="#footnote">*</a> pricing. Zero margin. Pay for what you use.</div>
</div>

<div class="costs-wrap">

<p>Fixed infrastructure ($${fixedTotal.toFixed(2)}/mo) is absorbed by Primitive Shell.</p>

<h2>Infrastructure</h2>
<table>
  <thead>
    <tr><th>Item</th><th>Provider</th><th>Monthly</th><th>What &amp; Why</th></tr>
  </thead>
  <tbody>
${infraRows}
  </tbody>
  <tfoot>
    <tr class="total"><td>Total fixed</td><td></td><td>$${fixedTotal.toFixed(2)}/mo</td><td></td></tr>
  </tfoot>
</table>

<h2>Per-primitive costs</h2>
${primSections}

<p class="updated" id="footnote">* Agents pay only the listed USDC price &mdash; no gas fees. x402 uses EIP-3009 meta-transactions: the agent signs off-chain, the facilitator submits the transaction and pays Base chain gas. Primitive Shell absorbs the facilitator settlement fee ($0.001/tx after the first 1,000/month). Operations priced at $0.001 (&ldquo;x402 floor&rdquo;) are the minimum the protocol needs to identify the caller&rsquo;s wallet. This revenue covers protocol overhead (caller identification, ownership scoping, abuse prevention) &mdash; it is not a provider pass-through cost.</p>
<p class="updated">Generated from <a href="https://github.com/primsh/prim.sh/blob/main/docs/costs.yaml">docs/costs.yaml</a> + prim.yaml files. Prices reflect current provider rates and may change. See <a href="/terms">Terms of Service</a> for details.</p>

</div>

${footer}
<img src="/assets/banner.jpg" alt="" class="img-fade" style="width:100%;display:block;margin:0;padding:0">
</body>
</html>
`;
}

// ── Write ──────────────────────────────────────────────────────────────────

console.log(CHECK_MODE ? "Mode: check\n" : "Mode: generate\n");

applyOrCheck(resolve(ROOT, "docs/costs.md"), renderMarkdown());
applyOrCheck(resolve(ROOT, "site/costs/index.html"), renderHtml());

if (CHECK_MODE && process.exitCode) {
	console.error("\nCost files are out of date. Run: pnpm gen:costs");
} else if (CHECK_MODE) {
	console.log("\nAll cost files are up to date.");
} else {
	console.log("\nDone.");
}
