#!/usr/bin/env bash
# metrics-snapshot.sh — Snapshot /v1/metrics from all live prims
#
# Appends a timestamped JSON line per service to /var/log/prim-metrics.log
# Designed for cron (every 6 hours) to persist metrics across service restarts.
#
# SERVICES is generated by `pnpm gen` from prim.yaml status:live fields.
# Do not edit manually — run `pnpm gen` after adding or removing a primitive.
#
# Usage: bash metrics-snapshot.sh

set -euo pipefail

LOG_FILE="/var/log/prim-metrics.log"
TIMEOUT=10

# BEGIN:PRIM:SERVICES
SERVICES=(wallet faucet spawn store email search infer)
# END:PRIM:SERVICES

ts=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

for svc in "${SERVICES[@]}"; do
  url="https://$svc.prim.sh/v1/metrics"
  body=$(curl -sf --max-time "$TIMEOUT" "$url" 2>/dev/null || echo '{"error":"unreachable"}')
  echo "{\"ts\":\"$ts\",\"service\":\"$svc.prim.sh\",\"metrics\":$body}" >> "$LOG_FILE"
done
