#!/usr/bin/env bash
# metrics-snapshot.sh — Snapshot /v1/metrics from all live prims
#
# Appends a timestamped JSON line per service to /var/log/prim-metrics.log
# Designed for cron (every 6 hours) to persist metrics across service restarts.
#
# ENDPOINTS is generated by `pnpm gen` from prim.yaml status:live fields.
# Do not edit manually — run `pnpm gen` after adding or removing a primitive.
#
# Usage: bash metrics-snapshot.sh

set -euo pipefail

LOG_FILE="/var/log/prim-metrics.log"
TIMEOUT=10

# BEGIN:PRIM:ENDPOINTS
ENDPOINTS=(
  "https://wallet.prim.sh/v1/metrics"
  "https://faucet.prim.sh/v1/metrics"
  "https://spawn.prim.sh/v1/metrics"
  "https://store.prim.sh/v1/metrics"
  "https://email.prim.sh/v1/metrics"
  "https://search.prim.sh/v1/metrics"
  "https://infer.prim.sh/v1/metrics"
)
# END:PRIM:ENDPOINTS

ts=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

for url in "${ENDPOINTS[@]}"; do
  service=$(echo "$url" | sed 's|https://||;s|/v1/metrics||')
  body=$(curl -sf --max-time "$TIMEOUT" "$url" 2>/dev/null || echo '{"error":"unreachable"}')
  echo "{\"ts\":\"$ts\",\"service\":\"$service\",\"metrics\":$body}" >> "$LOG_FILE"
done
