version: "1"
build:
  command: "pnpm -r lint && pnpm -r typecheck"
  timeout_seconds: 120
test:
  command: "pnpm -r test"
  timeout_seconds: 120
task_loop:
  task_file: "TASKS.md"
  implement_agent: cursor
  reviewer_agent: claude
  review_enabled: false
  review_checklist: "typescript-review"
  triage_enabled: false
  planning_enabled: false
  rescue_enabled: false
  max_retries_per_task: 0
  commit_to_main: false
  autogenerate_when_empty: false
